# Generated by Django 2.1.7 on 2019-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('doy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('season', models.CharField(choices=[('Growing', 'Growing'), ('NonGrowing', 'NonGrowing'), ('Shoulder', 'Shoulder')], max_length=10)),
                ('treatment', models.CharField(max_length=2)),
                ('n_replicates', models.IntegerField()),
                ('r_avg_umol_m2_s', models.FloatField()),
                ('resp_stdev', models.FloatField(blank=True, null=True)),
                ('moist_avg_cm3_cm_3', models.FloatField()),
                ('moist_stdev', models.FloatField(blank=True, null=True)),
                ('stemp_avg_c', models.FloatField()),
                ('stemp_sd_c', models.FloatField(blank=True, null=True)),
                ('warming_start', models.FloatField()),
                ('ecosystem_type', models.CharField(choices=[('BorealForest', 'BorealForest'), ('Desert', 'Desert'), ('Meadow', 'Meadow'), ('N_Shrubland', 'N_Shrubland'), ('S_Shrubland', 'S_Shrubland'), ('TemperateAgriculture', 'TemperateAgriculture'), ('TemperateForest', 'TemperateForest'), ('TemperateGrassland', 'TemperateGrassland'), ('WetSedgeTundra', 'WetSedgeTundra')], max_length=15)),
                ('sand_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('silt_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('clay_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
